name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - pip=23.2.1
  - mlflow=2.7.0
  - hydra-core=1.3.2
  - pip:
      - wandb==0.15.10
      - protobuf==3.20.*
      - hydra-joblib-launcher==1.2.0
